# Generated by Django 3.0.4 on 2020-03-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('PD_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('ramp_up_by_year', models.CharField(blank=True, max_length=200, null=True)),
                ('fh_year', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_fh', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fc_year', models.PositiveIntegerField(blank=True, null=True)),
                ('warranty_duration_new_product', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warranty_duration_repaired_product', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('AD_remarks', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airframer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LRU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=30, unique=True)),
                ('repair_lvl', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=30, null=True)),
                ('type_lru', models.CharField(blank=True, choices=[('SFE', 'SFE'), ('BFE', 'BFE'), ('SSFE', 'SSFE'), ('Option', 'Option'), ('SFE/BFE', 'SFE/BFE')], max_length=10, null=True)),
                ('ramp_up_year', models.CharField(blank=True, max_length=200, null=True)),
                ('export_control', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('PBD_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('mtbf', models.PositiveIntegerField(blank=True, null=True)),
                ('mtbur', models.PositiveIntegerField(blank=True, null=True)),
                ('nff_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('tte1', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('EP_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('g_mtbur', models.PositiveIntegerField(blank=True, null=True)),
                ('specified_mtbf', models.PositiveIntegerField(blank=True, null=True)),
                ('g_mtbf', models.PositiveIntegerField(blank=True, null=True)),
                ('specified_nff', models.PositiveIntegerField(blank=True, null=True)),
                ('g_dmc_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('g_dmc_ac', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('spare_price', models.PositiveIntegerField(blank=True, null=True)),
                ('warranty_duration_new_product', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warranty_duration_repaired_product', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('specified_mtte1', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('C_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('cpp_cci', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('cpp_asw', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('cpp_repair', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('cpp_nff', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('cost_dmc_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('cost_dmc_ac', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('ED_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('aircraft', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APILS.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='LruDenomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SruDenomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SRU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=30, unique=True)),
                ('repair_lvl', models.SmallIntegerField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('export_control', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('PBD_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('mtbf', models.IntegerField(blank=True, null=True)),
                ('EP_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('warranty_duration_new_product', models.SmallIntegerField(blank=True, null=True)),
                ('warranty_duration_repaired_product', models.SmallIntegerField(blank=True, null=True)),
                ('C_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('cpp_cci', models.CharField(blank=True, max_length=100, null=True)),
                ('cpp_asw', models.CharField(blank=True, max_length=100, null=True)),
                ('cpp_repair', models.CharField(blank=True, max_length=100, null=True)),
                ('ED_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('lru', models.ManyToManyField(to='APILS.LRU')),
                ('sru_denomination', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APILS.SruDenomination')),
            ],
        ),
        migrations.AddField(
            model_name='lru',
            name='lru_denomination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APILS.LruDenomination'),
        ),
        migrations.AddField(
            model_name='lru',
            name='product_line',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APILS.ProductLine'),
        ),
        migrations.AddField(
            model_name='lru',
            name='system_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APILS.SystemName'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='airframer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APILS.Airframer'),
        ),
    ]
