# Generated by Django 3.0.4 on 2020-03-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APILS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sru',
            name='lru',
        ),
        migrations.AddField(
            model_name='sru',
            name='lru',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APILS.LRU'),
        ),
    ]
